modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="lamon_by_coring"
version="0.0.1"
displayName="lamon by Coring"
credits="Created using mod maker MCreator - https://mcreator.net"
displayURL="https://mcreator.net"
authors="Coring, MCreator"

[[dependencies.lamon_by_coring]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




